Forgot to install casperjs' package.json.
Lack of package.json leads to an error:
  CasperError: Cannot find package.json at /usr/share/casperjs-1.1_beta3/package.json